### ISSUE TITLE
[Suggestion] Patch via hex instead of unpacking the archive

### ISSUE THREAD

**Issue by htv04** [DarkMatterCore/ww-43db-patcher#1]
I took a quick glance through the code, and forgive me if I'm wrong, but it seems like the program unpacks the System Menu archive to patch the 43DB files and repacks it. It might be faster to patch the 43DB via hex, so the archive doesn't have to be unpacked and repacked. The offset for the WiiWare 43DB for the USA System Menu is 0x6253B0, with a length of 0x208. You can fill this with 0x5A5A5A00 in order to patch the 43DB out. ~~I'm not sure what the offsets are for the PAL and JP system menus.~~ EDIT: Found the other offsets! For the PAL menu, it's 0x727430, and for the JPN menu, it's 0x62D8D0. They both share the same length as the USA 43DB.

I also have one more suggestion. Can you add an option to patch just the first two entries of the WiiWare 43DB (which are the EVC and the CMOC)? I think the rest of the 43DB is for WiiWare titles that really do only support 4:3 (I tested it with a few titles, such as Cave Story).

**Comment by DarkMatterCore** [comment]
@HTV04 Hi there, mate. Nice to meet you.

Don't worry, it's okay. The U8 archive isn't fully unpacked, though - it is fully loaded into RAM using ISFS functions, then parsed and modified using U8 functions, then written back to NAND using ISFS functions again.

Using paths relative to the root U8 archive directory, U8 nodes can be retrieved, which in turn are used to both read and write file specific data (such as 43DB files) to the U8 archive buffer in RAM.

As you can see, there's no full U8 unpacking going on - this is all custom U8 parsing code I wrote. The slowest operations would be reading and writing the ~8 MiB archive itself, and that's already pretty fast.

The point behind doing it this way is, precisely, not having to worry about hardcoding any offsets and sizes, since I'm not a big fan of such practices unless they're completely necessary. Theoretically speaking, this should work on Wii U consoles from all regions. It should also help other homebrew developers who wish to implement U8 archive parsing into their apps - most decent implementations I have seen are PC only and not written in plain C. :P

About the suggestion, sure, I can do it. Shouldn't be too hard to do.

**Comment by htv04** [comment]
Oh, I see. Sorry about the misunderstanding, that's really cool! Also, thanks!
