### ISSUE TITLE
Not Patching with themes installed

### ISSUE THREAD

**Issue by DraconicNEO** [DarkMatterCore/ww-43db-patcher#5]
Hello I have an issue where if I try to apply the patch with a theme installed it gives an error saying that there is an invalid offset. Is there any way to fix this issue? The theme I am using is DarkWii Plus from [Riiconnect24 themes](https://rc24.xyz/goodies/themes/). 
Thanks

**Comment by DarkMatterCore** [comment]
Hi there, mate.

Please check if you're using the latest release. v0.1 performed a very strict check while parsing directory nodes from the System Menu's U8 archive, which was removed in v0.2 because some (all?) custom U8 tools don't properly setup directory nodes. This includes theme installation tools.

**Comment by DraconicNEO** [comment]
> 
> 
> Hi there, mate.
> 
> Please check if you're using the latest release. v0.1 performed a very strict check while parsing directory nodes from the System Menu's U8 archive, which was removed in v0.2 because some (all?) custom U8 tools don't properly setup directory nodes. This includes theme installation tools.

That Fixed it, it seems the [version on OSC](https://oscwii.org/library/app/ww-43db-patcher) is outdated which is the one I was using.
